# Use the official MongoDB image
FROM mongo:8.0

# # Copy the entrypoint script into the container
# COPY ./src/dmaps/entrypoints/entrypoint_mongo.sh /usr/local/bin/entrypoint.sh
# RUN chmod +x /usr/local/bin/entrypoint.sh

# # Set the entrypoint
# ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]